baseURL = 'https://anxornot.github.io/blog-hugo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "m10c"

[params]
	author = "anxornot"
	description = "A blog about all things technical."
	
	[[params.social]]
		icon = "github"
		name = "GitHub"
		url = "https://github.com/anxornot"